
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_USER: trading_cards_db_user
      POSTGRES_PASSWORD: magic-pokemon-yu-gi-oh-3471
      POSTGRES_DB: trading_cards_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: trading_cards_db_user
      POSTGRES_PASSWORD: magic-pokemon-yu-gi-oh-3471
      POSTGRES_DB: trading_cards_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
