"""Added display_name column to User table.

Revision ID: 35fb711b128a
Revises: b3ff645e5f6d
Create Date: 2024-10-05 18:02:07.439622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fb711b128a'
down_revision = 'b3ff645e5f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=True))

    op.execute('UPDATE public."user" SET display_name = \'Nameless\'')
    op.alter_column('user', 'display_name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
